# Generated by Django 5.0 on 2025-12-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ministry_type', models.CharField(choices=[('EVANGELISM', 'Campus & High School Evangelism'), ('APOLOGETICS', 'Christian Apologetics Hub'), ('LEADERSHIP', 'Pastors Leadership Training'), ('STREET_KIDS', 'Street Kids Ministry')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on homepage')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ministry',
                'verbose_name_plural': 'ministries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MinistryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('featured_image', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ministry news',
                'verbose_name_plural': 'ministry news',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinistryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ministry page',
                'verbose_name_plural': 'ministry pages',
                'ordering': ['ministry', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MinistryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('OTHER', 'Other')], default='PDF', max_length=20)),
                ('file_url', models.URLField()),
                ('file_size', models.CharField(blank=True, help_text='e.g., 2.5 MB', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ministry resource',
                'verbose_name_plural': 'ministry resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
