# Generated by Django 5.0 on 2025-12-18 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ministrynews',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministrynews',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='ministries.ministry'),
        ),
        migrations.AddField(
            model_name='ministrypage',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ministries.ministry'),
        ),
        migrations.AddField(
            model_name='ministryresource',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ministries.ministry'),
        ),
        migrations.AddField(
            model_name='ministryresource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ministrypage',
            unique_together={('ministry', 'slug')},
        ),
    ]
