# Generated by Django 5.0 on 2025-12-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('CONFERENCE', 'Conference'), ('WEBINAR', 'Webinar'), ('WORKSHOP', 'Workshop'), ('QA_SESSION', 'Q&A Session'), ('TRAINING', 'Training Session')], default='CONFERENCE', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('timezone_name', models.CharField(default='Africa/Kigali', max_length=50)),
                ('speaker_name', models.CharField(blank=True, max_length=200)),
                ('speaker_bio', models.TextField(blank=True)),
                ('speaker_photo', models.URLField(blank=True, null=True)),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('thumbnail_image', models.URLField(blank=True, null=True)),
                ('youtube_live_url', models.URLField(blank=True, help_text='YouTube Live URL', null=True)),
                ('jitsi_room_name', models.CharField(blank=True, help_text='Jitsi room ID', max_length=100)),
                ('enable_jitsi', models.BooleanField(default=False, help_text='Enable interactive Jitsi session')),
                ('enable_youtube', models.BooleanField(default=True, help_text='Enable YouTube live stream')),
                ('recording_url', models.URLField(blank=True, help_text='YouTube video after event', null=True)),
                ('requires_registration', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live Now'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'event comment',
                'verbose_name_plural': 'event comments',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('reason_for_attending', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('attended', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'event registration',
                'verbose_name_plural': 'event registrations',
                'ordering': ['-registered_at'],
            },
        ),
    ]
