# Generated by Django 5.0 on 2025-12-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['gallery', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_photo', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'photo gallery',
                'verbose_name_plural': 'photo galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('SALVATION', 'Salvation'), ('HEALING', 'Healing'), ('TRANSFORMATION', 'Transformation'), ('STREET_KIDS', 'Street Kids Impact'), ('STUDENT', 'Student Life Change'), ('PASTOR', 'Pastor Testimony'), ('OTHER', 'Other')], default='TRANSFORMATION', max_length=20)),
                ('person_name', models.CharField(blank=True, help_text='Name of person giving testimony', max_length=200)),
                ('person_photo', models.URLField(blank=True, null=True)),
                ('person_location', models.CharField(blank=True, max_length=200)),
                ('excerpt', models.TextField(max_length=300)),
                ('story', models.TextField()),
                ('featured_image', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube video URL', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'testimony',
                'verbose_name_plural': 'testimonies',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('photos', models.JSONField(default=list, help_text='List of photo URLs')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('people_reached', models.IntegerField(default=0)),
                ('lives_impacted', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_stories', to='ministries.ministry')),
            ],
            options={
                'verbose_name': 'impact story',
                'verbose_name_plural': 'impact stories',
                'ordering': ['-event_date'],
            },
        ),
    ]
