# Generated by Django 5.0 on 2025-12-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('youtube_playlist_id', models.CharField(blank=True, max_length=50)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'playlist video',
                'verbose_name_plural': 'playlist videos',
                'ordering': ['playlist', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VideoLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('youtube_video_id', models.CharField(help_text='YouTube video ID', max_length=50)),
                ('youtube_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('SERMON', 'Sermon'), ('TEACHING', 'Teaching'), ('TESTIMONY', 'Testimony'), ('CONFERENCE', 'Conference'), ('TRAINING', 'Training'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video library',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
