# Generated by Django 5.0 on 2025-12-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='ministries.ministry'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='media.playlist'),
        ),
        migrations.AddField(
            model_name='videolibrary',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='ministries.ministry'),
        ),
    ]
